### ISSUE TITLE
authentication for cloning Koadic ?

### ISSUE THREAD

**Issue by toddehb** [offsecginger/koadic#1]
When doing `git clone https://github.com/zerosum0x0/koadic.git` on my Kali Linux I am asked for authentication. Using my Git User does not work

**Comment by offsecginger** [comment]
That's because @zerosum0x0 has archived their project. You've put an issue on the `offsecginger` fork of this code, which as far as I am aware is the latest version.

In order to pull from this repository, use the following command:

`git clone https://github.com/offsecginger/koadic`

Note that I did not change ANYTHING about the actual repository when I cloned it over, so the README does not have the updated repository information. Closing.
